### ISSUE TITLE
Missing emoji aliases

### ISSUE THREAD

**Issue by jefftriplett** [jsumners/alfred-emoji#78]
I couldn't tell if this was related to #76, but it looks like common aliases might have been dropped in the last update. 

An example is searching for `coffee` which brings up brown "brown heart" 🤎 and "coffin" ⚰️. 

TIL that it's labeled as "hot beverage" which search can't quite narrow down with either "hot beverage" or "hotbeverage". I can eventually get there by searching for "beverage" finding it.

Anyways, not a huge deal, but passing it along just in case this wasn't intended.

**Comment by jsumners** [comment]
Aliases are defined in https://unicode.org/emoji/charts/emoji-list.html and imported here through https://github.com/muan/emojilib. As such, we do not maintain the list of aliases. We'd need upstream to fill in the gaps and release a new version.

**Comment by jsumners** [comment]
I think `emojilib` maintains the aliases manually. I also think the maintainer is tired of maintaining the library (completely understandable). Before they released v3, I investigated parsing the atrocious Unicode data sets and building my own data to use in this application. I may need to revisit that.

**Comment by jefftriplett** [comment]
Thanks for the quick reply and the reference. I think I might have found the 1 in a million where it was accidently moved to the 🤎 .  https://github.com/muan/emojilib/pull/199 It might be fixed in a future update from the looks of things.

**Comment by berters** [comment]
@jsumners It definitely seems like something is off - you can see my example of "pray" to find U+1F64F - which used to work but can no longer be found.

![Screenshot 2022-02-03 at 08 51 26](https://user-images.githubusercontent.com/4118664/152310512-aec3a84c-9918-4937-b1ec-d2a1bc9d8c5d.gif)
.

**Comment by jsumners** [comment]
@berters please reread the thread.

**Comment by berters** [comment]
> @berters please reread the thread.

My apologies, seems like it's down to emojlib then.

**Comment by rmm5t** [comment]
Some of these aliases are being fixed in emojilib as we speak:
https://github.com/muan/emojilib/commits/main/dist

**Comment by cafesanu** [comment]
First, thanks for this alfred workflow @jsumners . I love it.

Now, I get it the emojilib is the one keeping the keywords, but something changed lately and now results are way of. For example, I use the bee emoji a lot, I used to do `emoji bee` and it would be the first result in the list, now it's a cow.

Let's compare what emojilib has vs the results:
<img width="116" alt="image" src="https://user-images.githubusercontent.com/4213098/165961178-873e11aa-e781-4549-b4c0-9eaf31b91fc9.png">
<img width="110" alt="image" src="https://user-images.githubusercontent.com/4213098/165961293-21c9966c-5301-48da-9296-162dac1f8793.png">
<img width="571" alt="image" src="https://user-images.githubusercontent.com/4213098/165961341-9a94163d-94fa-4d15-94e5-1cf6ce711ea9.png">

Now, let's be more exact. These are the emojis have the string in `bee` in emojilib. And this is the order or precedence I would expect them to have base on the position in the array:


As you can see, the string `bee` is in position `0` for the  🐝  emoji, vs in position `1` for 🐮  emoji. I would expect that the strings with higher position within the arrays would have more precedence. Just like, when I type `:bee` here in github, I get the bee First.

In conclusion, I would expect the following order based on emojilib:
## Position 0 to 5 (in any order since they all share position `0`?).
"🐝": [
"honey**bee**",
"animal",
"insect",
"nature",
"bug",
"spring",
"honey"
],
"🐞": [
"lady_**bee**tle",
"animal",
"insect",
"nature",
"ladybug"
],
"🍺": [
"**bee**r_mug",
"relax",
"beverage",
"drink",
"drunk",
"party",
"pub",
"summer",
"alcohol",
"booze"
],
"🍻": [
"clinking_**bee**r_mugs",
"relax",
"beverage",
"drink",
"drunk",
"party",
"pub",
"summer",
"alcohol",
"booze"
],
"🍻": [
"clinking_**bee**r_mugs",
"relax",
"beverage",
"drink",
"drunk",
"party",
"pub",
"summer",
"alcohol",
"booze"
],
"🪲": [
"**bee**tle",
"insect"
],

## Position 5 to 6 (in any order since they all share position `1`).
"🐮": [
"cow_face",
"**bee**f",
"ox",
"animal",
"nature",
"moo",
"milk"
],
"🐄": [
"cow",
"**bee**f",
"ox",
"animal",
"nature",
"moo",
"milk"
],
## Position 7 to 8 (in any order since they all share position `2`).
"🐂": [
"ox",
"animal",
"cow",
"**bee**f"
],
"🍔": [
"hamburger",
"meat",
"fast food",
"**bee**f",
"cheeseburger",
"mcdonalds",
"burger king"
],


Thanks!

**Comment by jefftriplett** [comment]
I'm going to go ahead and close my own issue. My main issue I was seeing was aliases not working that appear to be in `emojilib` (see https://github.com/muan/emojilib/blob/63532198d03123e5b75aa348bc00f6f36f18aac7/dist/emoji-en-US.json#L4804 for an example of my "emoji coffee" showing up blank example). 

I think the scope of comments has drifted to search relevance more than aliases not showing up. Feel free to re-open if you want.
