### ISSUE TITLE
v2.0.0 not working on Alfred 4

### ISSUE THREAD

**Issue by alenvuletic** [jsumners/alfred-emoji#93]
I've just updated the plugin to the newest version on Alfred 4 and workflow stops working entirely.

I hope you'll keep supporting Alfred 4 because you have a great workflow there.

Thanks!

**Comment by jsumners** [comment]
Note that it is highlighted very prominently at the top of the release notes that only v5 is supported -- https://github.com/jsumners/alfred-emoji/releases/tag/v2.0.0

However, that does not help when the workflow is automatically updating without consent. We need to issue an update against the v1 line that merely notifies if there is a new major version instead of downloading it and installing it. 

In the interim, I recommend downloading https://github.com/jsumners/alfred-emoji/releases/tag/v1.12.0 and disabling the auto update feature manually:

<details>
<summary>GIF</summary>

![disable-auto-update](https://user-images.githubusercontent.com/321201/196171098-a3c09c5c-c62b-43b4-bcc3-ce3e89f08f3e.gif)


</details>

<details>
<summary>Video</summary>


https://user-images.githubusercontent.com/321201/196171175-8a4a6224-65e9-4e38-88e0-9fe3c4504f3a.mp4



</details>

I cannot promise getting to this myself soon, but if anyone would like to contribute a fix for this, please target branch https://github.com/jsumners/alfred-emoji/tree/v1 (we'll need to port it to the main branch as well, but the primary concern is fixing v1 users).

**Comment by jsumners** [comment]
Please use https://github.com/jsumners/alfred-emoji/releases/tag/v1.12.1 to continue using this workflow on Alfred v4. To use alfred-emoji@2 or later, you'll need to update to Alfred v5.

**Comment by alenvuletic** [comment]
Hi @jsumners, unfortunately, every day update notification pops up and opens Alfred window which says I should update to the newest version.

Is there a way to suppress those notifications?

**Comment by jsumners** [comment]
Did you set the environment variable as outlined in the release notes and readme?

**Comment by alenvuletic** [comment]
@jsumners yes, it works now, thanks a lot!
